import jsPDF from 'jspdf'
import type { PostureReport } from '../analysis/postureEngine'

export async function generatePDF(report: PostureReport): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = 210
  const margin = 16
  const contentW = pageW - margin * 2
  let y = 0

  // Header bar
  pdf.setFillColor(16, 185, 129)
  pdf.rect(0, 0, pageW, 30, 'F')
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.text('PostureCheck', margin, 13)
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text('AI Posture Analysis Report', margin, 21)
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, pageW - margin, 21, { align: 'right' })

  y = 40

  // Score section
  pdf.setTextColor(15, 23, 42)
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Overall Posture Score', margin, y)
  y += 8

  const scoreColor = report.overallScore >= 85 ? [16, 185, 129] :
    report.overallScore >= 70 ? [59, 130, 246] :
    report.overallScore >= 50 ? [245, 158, 11] : [239, 68, 68]

  pdf.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2])
  pdf.circle(margin + 15, y + 12, 14, 'F')
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(18)
  pdf.setFont('helvetica', 'bold')
  pdf.text(`${report.overallScore}`, margin + 15, y + 14, { align: 'center' })

  pdf.setTextColor(15, 23, 42)
  pdf.setFontSize(16)
  pdf.setFont('helvetica', 'bold')
  pdf.text(report.overallGrade, margin + 35, y + 10)
  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  pdf.setTextColor(100, 116, 139)
  pdf.text(`Posture Type: ${report.postureType}`, margin + 35, y + 18)
  y += 35

  // Annotated image
  if (report.annotatedImageUrl) {
    try {
      const imgData = report.annotatedImageUrl
      const imgW = 80
      const imgH = 100
      pdf.addImage(imgData, 'JPEG', pageW - margin - imgW, 38, imgW, imgH)
    } catch (_) {}
  }

  // Summary
  pdf.setFillColor(240, 253, 249)
  pdf.roundedRect(margin, y, contentW, 24, 3, 3, 'F')
  pdf.setFontSize(10)
  pdf.setTextColor(15, 23, 42)
  pdf.setFont('helvetica', 'normal')
  const summaryLines = pdf.splitTextToSize(report.summary, contentW - 8)
  pdf.text(summaryLines.slice(0, 3), margin + 4, y + 8)
  y += 30

  // Zone breakdown
  pdf.setFontSize(13)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(15, 23, 42)
  pdf.text('Zone Analysis', margin, y)
  y += 8

  report.zones.forEach(zone => {
    const gradeColor = zone.grade === 'Excellent' ? [16, 185, 129] :
      zone.grade === 'Good' ? [59, 130, 246] :
      zone.grade === 'Fair' ? [245, 158, 11] : [239, 68, 68]

    pdf.setFillColor(248, 250, 252)
    pdf.roundedRect(margin, y, contentW, 20, 2, 2, 'F')
    pdf.setFillColor(gradeColor[0], gradeColor[1], gradeColor[2])
    pdf.rect(margin, y, 3, 20, 'F')

    pdf.setFontSize(11)
    pdf.setFont('helvetica', 'bold')
    pdf.setTextColor(15, 23, 42)
    pdf.text(zone.name, margin + 8, y + 7)
    pdf.setFontSize(9)
    pdf.setFont('helvetica', 'normal')
    pdf.setTextColor(100, 116, 139)
    const detailLines = pdf.splitTextToSize(zone.detail, contentW - 60)
    pdf.text(detailLines[0], margin + 8, y + 14)

    pdf.setFillColor(gradeColor[0], gradeColor[1], gradeColor[2])
    pdf.roundedRect(pageW - margin - 28, y + 5, 28, 10, 2, 2, 'F')
    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(9)
    pdf.setFont('helvetica', 'bold')
    pdf.text(`${zone.grade} ${zone.score}`, pageW - margin - 14, y + 11.5, { align: 'center' })

    y += 24
  })

  y += 6

  // Posture type description
  pdf.setFillColor(238, 237, 254)
  pdf.roundedRect(margin, y, contentW, 22, 3, 3, 'F')
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(60, 52, 137)
  pdf.text(`Posture Type: ${report.postureType}`, margin + 4, y + 8)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(9)
  const typeLines = pdf.splitTextToSize(report.postureTypeDescription, contentW - 8)
  pdf.text(typeLines[0], margin + 4, y + 16)
  y += 30

  // Disclaimer
  pdf.setFillColor(254, 252, 232)
  pdf.roundedRect(margin, y, contentW, 18, 2, 2, 'F')
  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'italic')
  pdf.setTextColor(120, 100, 20)
  const disclaimer = 'Medical Disclaimer: This report is generated by AI for informational purposes only and does not constitute medical advice. Results should be reviewed by a qualified physiotherapist or healthcare professional. Do not use this as a sole basis for diagnosis or treatment.'
  const discLines = pdf.splitTextToSize(disclaimer, contentW - 8)
  pdf.text(discLines, margin + 4, y + 6)

  // Footer
  pdf.setFillColor(16, 185, 129)
  pdf.rect(0, 282, pageW, 15, 'F')
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(8)
  pdf.setFont('helvetica', 'normal')
  pdf.text('PostureCheck — posturecheck.vercel.app', margin, 291)
  pdf.text('Powered by AI. For clinical use, consult Phrapy Physiotherapy Center, Wakad, Pune.', pageW - margin, 291, { align: 'right' })

  pdf.save(`posture-report-${Date.now()}.pdf`)
}
